// Mock data for dashboard UI development
// Remove once database is connected

// ─── Item Types ─────────────────────────────────────────

export const itemTypes = [
  { id: "type-snippet", name: "Snippet", icon: "Code", color: "#3b82f6", isSystem: true },
  { id: "type-prompt", name: "Prompt", icon: "Sparkles", color: "#8b5cf6", isSystem: true },
  { id: "type-command", name: "Command", icon: "Terminal", color: "#f97316", isSystem: true },
  { id: "type-note", name: "Note", icon: "StickyNote", color: "#fde047", isSystem: true },
  { id: "type-link", name: "Link", icon: "Link", color: "#10b981", isSystem: true },
  { id: "type-file", name: "File", icon: "File", color: "#6b7280", isSystem: true },
  { id: "type-image", name: "Image", icon: "Image", color: "#ec4899", isSystem: true },
] as const;

// ─── User ───────────────────────────────────────────────

export const currentUser = {
  id: "user-1",
  name: "Kunal",
  email: "kunalmugalkhod007@gmail.com",
  image: null,
  isPro: true,
};

// ─── Collections ────────────────────────────────────────

export const collections = [
  {
    id: "col-1",
    name: "React Patterns",
    description: "Common hooks and components",
    isFavorite: true,
    itemCount: 12,
    typeIds: ["type-snippet", "type-link"],
    updatedAt: "2026-03-14T10:00:00Z",
  },
  {
    id: "col-2",
    name: "Context Files",
    description: "Project context for LLMs",
    isFavorite: true,
    itemCount: 5,
    typeIds: ["type-file"],
    updatedAt: "2026-03-13T08:00:00Z",
  },
  {
    id: "col-3",
    name: "Interview Prep",
    description: "Algorithms and system design",
    isFavorite: true,
    itemCount: 24,
    typeIds: ["type-prompt"],
    updatedAt: "2026-03-12T14:00:00Z",
  },
  {
    id: "col-4",
    name: "Python Snippets",
    description: "Data processing scripts",
    isFavorite: false,
    itemCount: 8,
    typeIds: ["type-snippet"],
    updatedAt: "2026-03-10T16:00:00Z",
  },
];

// ─── Items ──────────────────────────────────────────────

export const items = [
  {
    id: "item-1",
    title: "useDebounce hook",
    contentType: "text" as const,
    content: "import { useState, useEffect } from 'react'; export function useDebounce<T>(value: T, delay: number...",
    typeId: "type-snippet",
    language: "typescript",
    isFavorite: true,
    isPinned: false,
    tags: ["react", "hooks", "frontend"],
    createdAt: "2026-03-15T10:00:00Z",
  },
  {
    id: "item-2",
    title: "Explain code to junior dev",
    contentType: "text" as const,
    content: "Explain the following code snippet as if you are talking to a junior developer who just started lear...",
    typeId: "type-prompt",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["ai"],
    createdAt: "2026-03-14T08:00:00Z",
  },
  {
    id: "item-3",
    title: "Docker cleanup all",
    contentType: "text" as const,
    content: "docker system prune -a --volumes",
    typeId: "type-command",
    language: "bash",
    isFavorite: false,
    isPinned: false,
    tags: ["docker"],
    createdAt: "2026-03-12T14:00:00Z",
  },
  {
    id: "item-4",
    title: "Meeting notes - Q3 Planning",
    contentType: "text" as const,
    content: "# Q3 Planning - Focus on performance improvements - Migrate to Next.js 16 - Implement new AI featur...",
    typeId: "type-note",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: [],
    createdAt: "2026-03-08T09:00:00Z",
  },
  {
    id: "item-5",
    title: "Next.js 16 Docs",
    contentType: "url" as const,
    content: "https://nextjs.org/docs",
    typeId: "type-link",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["react", "frontend"],
    createdAt: "2026-03-01T12:00:00Z",
  },
  {
    id: "item-6",
    title: "Data processing script",
    contentType: "text" as const,
    content: "import pandas as pd\ndef process_data(file_path): df = pd.read_csv(file_path) df = df.dropna...",
    typeId: "type-snippet",
    language: "python",
    isFavorite: false,
    isPinned: false,
    tags: ["python"],
    createdAt: "2026-02-15T16:00:00Z",
  },
  {
    id: "item-7",
    title: "Tailwind CSS Grid Layout",
    contentType: "text" as const,
    content: '<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">  <div>1</div> <div>2</div>...',
    typeId: "type-snippet",
    language: "tsx",
    isFavorite: false,
    isPinned: false,
    tags: ["frontend"],
    createdAt: "2026-03-13T11:00:00Z",
  },
  {
    id: "item-8",
    title: "System Prompt: Code Reviewer",
    contentType: "text" as const,
    content: "You are an expert code reviewer. Review the following code for security vulnerabilities, performance...",
    typeId: "type-prompt",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["ai"],
    createdAt: "2026-03-10T15:00:00Z",
  },
  {
    id: "item-9",
    title: "Git Reset Hard",
    contentType: "text" as const,
    content: "git reset --hard HEAD~1",
    typeId: "type-command",
    language: "bash",
    isFavorite: false,
    isPinned: false,
    tags: ["git"],
    createdAt: "2026-03-08T13:00:00Z",
  },
  {
    id: "item-10",
    title: "Architecture Diagram",
    contentType: "file" as const,
    content: null,
    fileUrl: "/mock/architecture-diagram.png",
    fileName: "architecture-diagram.png",
    typeId: "type-image",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: [],
    createdAt: "2026-03-01T10:00:00Z",
  },
];
